services:
  justinpaulhammond:
    build: .
    restart: always
    networks:
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
    env_file:
      - src/.env

networks:
  traefik:
    name: traefik
    external: true
