version: "3.7"

services:
    justinpaulhammond:
        build: .
        restart: always
        container_name: justinpaulhammond
        volumes:
            - ./src:/var/www/html
        networks:
            - traefik
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik
            - traefik.frontend.rule=Host:justin.localhost
            - traefik.port=80

networks:
    traefik:
        external:
            name: traefik
