services:
  justinpaulhammond:
    build:
      args:
        PROD: true
    deploy:
      replicas: 2
    mem_limit: '512m'
    healthcheck:
      test: ['CMD', 'curl', '--silent', '--output', '/dev/null', '--show-error', '--fail', 'http://localhost/up']
      start_period: 10s
      start_interval: 1s
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      # TODO: send these to elasticsearch
      - ./src/storage/logs:/var/www/html/storage/logs
