services:
  justinpaulhammond:
    build:
      args:
        PROD: true
    deploy:
      replicas: 2
    mem_limit: '512m'
    healthcheck:
      test: ['CMD', 'curl', '--silent', '--output', '/dev/null', '--show-error', '--fail', 'http://localhost/up']
      start_period: 10s
      start_interval: 1s
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - 'traefik.http.routers.justinpaulhammond.rule=Host(`justinpaulhammond.com`) || Host(`www.justinpaulhammond.com`)'
      - 'traefik.http.routers.justinpaulhammond.tls=true'
      - 'traefik.http.routers.justinpaulhammond.tls.certresolver=letsencrypt'
    volumes:
      - ./src/storage/app:/var/www/html/storage/app
      - ./src/storage/logs:/var/www/html/storage/logs
      - ./src/database/database.sqlite:/var/www/html/database/database.sqlite
