services:
  justinpaulhammond:
    build:
      args:
        PROD: true
    deploy:
      replicas: 2
    mem_limit: '512m'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      start_period: 10s
      start_interval: 1s
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - 'traefik.http.routers.justinpaulhammond.rule=Host(`justinpaulhammond.com`, `www.justinpaulhammond.com`)'
      - 'traefik.http.routers.justinpaulhammond.tls=true'
      - 'traefik.http.routers.justinpaulhammond.tls.certresolver=letsencrypt'
    volumes:
      - ./src/storage:/var/www/html/storage
