version: '3.7'

services:

    ## Use latest Nginx to serve
    nginx_justinpaulhammond:
        image: nginx:latest
        restart: always
        container_name: 'justinpaulhammond-nginx'
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - traefik
        labels:
            - traefik.enabled=true
            - traefik.backend=nginx
            - traefik.docker.network=traefik
            - traefik.frontend.rule=Host:justin.localhost
            - traefik.port=80

    ## Use latest PHP
    php_justinpaulhammond:
        image: php:fpm
        restart: always
        container_name: 'justinpaulhammond-php'
        volumes:
            - ./:/var/www
        networks:
            - traefik

networks:
    traefik:
        external:
            name: traefik