version: "3.8"
services:
  justinpaulhammond:
    deploy:
      replicas: 2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - traefik.frontend.rule=Host:justinpaulhammond.com,www.justinpaulhammond.com
    volumes:
      - ./src/storage:/var/www/html/storage
