version: "3.7"

services:
    justinpaulhammond:
        build: blog-dockerfile
            context: .
        restart: always
        container_name: justinpaulhammond
        networks:
            - traefik
            - laraview
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik
            - traefik.frontend.rule=Host:justinpaulhammond.com,www.justinpaulhammond.com
            - traefik.port=80

networks:
    traefik:
        external:
            name: traefik
    laraview:
        external:
            name: laraview
