services:
  justinpaulhammond:
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.justinpaulhammond.rule=Host(`justinpaulhammond.localhost`)'
    networks:
      - traefik
    volumes:
      - ./src:/var/www/html

networks:
  traefik:
    name: traefik
    external: true
