services:
  justinpaulhammond:
    build: .
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.port=80

networks:
  traefik:
    name: traefik
