version: "3.7"

services:

    ## Use latest Nginx to serve
    nginx_justinpaulhammond:
        image: nginx:latest
        restart: always
        container_name: justinpaulhammond-nginx
        volumes:
            - ./site:/var/www/html/site
            - ./blog:/var/www/html/blog
            - ./nginx-blog.conf:/etc/nginx/conf.d/default.conf
        networks:
            - traefik
        labels:
            - traefik.enabled=true
            - traefik.docker.network=traefik
            - traefik.frontend.rule=Host:justinpaulhammond.com,www.justinpaulhammond.com
            - traefik.port=80

    ## Use latest PHP
    php_justinpaulhammond:
        image: php:fpm
        restart: always
        container_name: justinpaulhammond-php
        volumes:
            - ./site:/var/www/html/site
            - ./blog:/var/www/html/blog
        networks:
            - traefik

networks:
    traefik:
        external:
            name: traefik
