services:
  justinpaulhammond:
    build:
      args:
        PROD: true
    ports:
      - 8100:80
    cpus: 1
    mem_limit: '1024m'
    healthcheck:
      test: ['CMD', 'curl', '--silent', '--output', '/dev/null', '--show-error', '--fail', 'http://localhost/up']
      start_period: 10s
      start_interval: 1s
      interval: 30s
      timeout: 10s
      retries: 3
