version: "3.8"
services:
  justinpaulhammond:
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "128M"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.http.routers.justinpaulhammond.rule=Host(`justinpaulhammond.com`, `www.justinpaulhammond.com`)"
      - "traefik.http.routers.justinpaulhammond.tls=true"
      - "traefik.http.routers.justinpaulhammond.tls.certresolver=letsencrypt"
    volumes:
      - ./src/storage:/var/www/html/storage
